spring:
  application:
    name: culinary-agent
  ai:
    google:
      genai:
        api-key: ${GOOGLE_GENAI_API_KEY}
        chat:
          options:
            model: ${GEMINI_GENAI_MODEL:gemini-3-flash-preview}
            thinking-level: LOW
    model:
      audio:
        speech: elevenlabs
    elevenlabs:
      api-key: ${ELEVENLABS_API_KEY}
      tts:
        options:
          model-id: ${ELEVENLABS_TTS_MODEL_ID:eleven_flash_v2_5}